[project]
slug = "keyword-assistant"
name = "生意参谋关键词排行"
category = "淘系" 
version = "1.2.0"
author = "YiqiWork"
description = "通过生意参谋获取热搜 / 飙升 / 新词排行榜的关键词和关键词相关分析作为拓展词"
icon_url ="https://img.alicdn.com/imgextra/i4/O1CN01ryp9zX1fDE0AzYiQP_!!6000000003972-2-tps-160-160.png"
requires-python = ">=3.10"
dependencies = ["httpx>=0.27"]